Various changes per latest beta
music-assistant/music-assistant.github.io pull request #41
Opened 2024-04-29 06:00 UTC by OzGav

2024-04-29 14:36 UTC, jozefKruszynski requested changes
Couple of minimal changes that I think might make sense, but I could be wrong.

2024-04-29 14:36 UTC, jozefKruszynski commented on docs/music-providers/filesystem.md
> +- Embedded album thumbs will be extracted from audio files. However, you can improve performance and save disk space by providing a single local artwork file vice embedding the same artwork in all fi
```suggestion
- Embedded album thumbs will be extracted from audio files. However, you can improve performance and save disk space by providing a single local artwork file vs. embedding the same artwork in all files.
```

2024-04-29 14:36 UTC, jozefKruszynski commented on docs/ui.md
> +The tracks and albums section are collapsible. The view above shows them both collapsed. The tracks section shows ALL tracks that are in the library or that are available across all of the providers.
```suggestion
The tracks and albums sections are collapsible. The view above shows them both collapsed. The tracks section shows ALL tracks that are in the library or that are available across all of the providers. A red dot on the library icon ![image](assets/icons/library-icon.png) indicates that the viewed results are filtered to only show items that are in the library. To see what albums any given track is on you can either sort alphabetically or click on one and use the context menu and SHOW INFO. 
```

2024-04-29 22:04 UTC, OzGav commented on docs/music-providers/filesystem.md
> +- Embedded album thumbs will be extracted from audio files. However, you can improve performance and save disk space by providing a single local artwork file vice embedding the same artwork in all fi
LGTM

2024-04-30 03:49 UTC, jozefKruszynski approved these changes

2024-04-30 03:49 UTC, merged