Various improvements
music-assistant/music-assistant.github.io pull request #59
Opened 2024-05-22 00:02 UTC by OzGav

2024-05-22 15:10 UTC, FancyNerd92 commented
i have problem with MA is not showing on Media Sources on Home Assistant. Any ideas?

2024-05-22 21:56 UTC, OzGav commented
> i have problem with MA is not showing on Media Sources on Home Assistant. Any ideas?

Why are you asking in a PR for the documentation?

2024-05-24 05:08 UTC, jozefKruszynski requested changes

2024-05-24 05:08 UTC, jozefKruszynski commented on docs/ui.md
> +Results, limited to a maaximum of 50 items, are returned in the six categories of Top Results, Tracks, Artists, Albums, Playlists and Radio. Context sensitive menus are available for the various item
Double "a" in maximum

2024-05-24 05:23 UTC, jozefKruszynski approved these changes

2024-05-24 05:23 UTC, merged